sudo: required
language: java
jdk:
  - oraclejdk8
before_install:
  - chmod +x mvnw
services:
  - docker
cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - docker
notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - bren@juanantonio.info
script:
  - ./mvnw clean test
after_success:
  - bash <(curl -s https://codecov.io/bash)