
#spring.profiles.active: "pro"

redis.host: 192.168.99.100
redis.port: 6379


cache.redis.host: 192.168.99.100
cache.redis.port: 6379

#Pool
cache.redis.minIdle: 8
cache.redis.maxIdle: 500
cache.redis.maxActive: 2000
cache.redis.maxWait: 10000
cache.redis.timeOut: 0

#spring.cache.type: redis
#spring.redis.host: 192.168.99.100
#spring.redis.port: 6379

spring.datasource.postgres.driverClassName: org.postgresql.Driver
#spring.datasource.postgres.driver-class: org.postgresql.Driver
spring.datasource.postgres.jdbc-url: jdbc:postgresql://localhost:5432/oculus
spring.datasource.postgres.username: postgres
spring.datasource.postgres.password: postgresql
spring.datasource.postgres.type: com.zaxxer.hikari.HikariDataSource

---

spring:
  profiles: test

  #main.banner-mode: "off"

---

spring:
  profiles: pro

spring.datasource.postgres.driverClassName: org.postgresql.Driver
spring.datasource.postgres.url: jdbc:postgresql://192.168.2.34:5432/oculus
spring.datasource.postgres.username: postgres
spring.datasource.postgres.password: postgresql

